### ISSUE TITLE
Ratto-Docker DK37 step advance issue as step 2 (main page) is overwriting prior work

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas/MouseBrainAtlas_dev#8]
Hi Alex,

DK37 (sagittal NTB)
1- started Jan2 and ran to DK_37_raw_thumbnail (completed)
2 - stopped because of memory concerns on 10HDD 1
3- Jan 14- Reopened Docker with Alex's permission -
4.  Dashboard showed  Step 2 highlighted (create initial thumbnails) so selected this
5. Currently running but it seems to be writing over all prior raw thumbnail conversions for this stack

**Comment by CodingDonky** [comment]
Hi Beth,

Yes if you rerun a step it will overwrite what has previously been run.

Also in the email you sent me you indicated that thumbnails existed but that it is still on the thumbnail step. This is because the folder "raw_thumbnails" contains preliminary thumbnails of every image, including placeholders, that have been globally normalized for viewing purposes. The thumbnail step does not correspond to these viewing thumbnails, it corresponds to downsampled versions of images located in the sorted_filenames text file
